//
//  MessagesViewController.swift
//  MessagesExtension
//
//  Created by Yogesh Murugesh on 10/10/16.
//  Copyright © 2016 Mallow Technologies Private Limited. All rights reserved.
//

import UIKit
import Messages

class MessagesViewController: MSMessagesAppViewController, StartGameViewControllerDelegate, CreateGameViewControllerDelegate {
    
    // MARK: - View Life Cycle

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Conversation Handling
    
    override func willBecomeActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the inactive to active state.
        // This will happen when the extension is about to present UI.
        
        // Use this method to configure the extension and restore previously stored state.
        presentView(forconversation: conversation, withStyle: presentationStyle, fromStartGame: false)
    }
    
    override func didResignActive(with conversation: MSConversation) {
        // Called when the extension is about to move from the active to inactive state.
        // This will happen when the user dissmises the extension, changes to a different
        // conversation or quits Messages.
        
        // Use this method to release shared resources, save user data, invalidate timers,
        // and store enough state information to restore your extension to its current state
        // in case it is terminated later.
    }
   
    override func didReceive(_ message: MSMessage, conversation: MSConversation) {
        // Called when a message arrives that was generated by another instance of this
        // extension on a remote device.
        
        // Use this method to trigger UI updates in response to the message.
    }
    
    override func didStartSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user taps the send button.
    }
    
    override func didCancelSending(_ message: MSMessage, conversation: MSConversation) {
        // Called when the user deletes the message without sending it.
    
        // Use this to clean up state related to the deleted message.
    }
    
    override func willTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called before the extension transitions to a new presentation style.
    
        // Use this method to prepare for the change in presentation style.
        if presentationStyle == .expanded {
            presentView(forconversation: activeConversation!, withStyle: presentationStyle, fromStartGame: true)
        } else {
            presentView(forconversation: activeConversation!, withStyle: presentationStyle, fromStartGame: false)
        }
    }
    
    override func didTransition(to presentationStyle: MSMessagesAppPresentationStyle) {
        // Called after the extension transitions to a new presentation style.
    
        // Use this method to finalize any behaviors associated with the change in presentation style.
    }

    
    // MARK: - Custom Methods
    
    private func presentView(forconversation: MSConversation, withStyle: MSMessagesAppPresentationStyle, fromStartGame: Bool) {
        // Determine the controller to present.
        print(forconversation.selectedMessage)
        var controller: UIViewController = UIViewController()
        if forconversation.selectedMessage == nil && !fromStartGame && withStyle != .expanded {
            controller = instantiateStartGameView()!
        } else if forconversation.selectedMessage == nil && ( fromStartGame || withStyle == .expanded ){
            controller = instantiateCreateGameView()!
        } else if forconversation.selectedMessage != nil {
            let hangMessage = HangMessage(forconversation)
            controller = instantiateAnswerGameView(hangMessage)!
        }
        
        // Remove any existing child controllers.
        for child in childViewControllers {
            child.willMove(toParentViewController: nil)
            child.view.removeFromSuperview()
            child.removeFromParentViewController()
        }
        
        // Embed the new controller.
        addChildViewController(controller)
        
        controller.view.frame = view.bounds
        controller.view.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(controller.view)
        
        controller.view.leftAnchor.constraint(equalTo: view.leftAnchor).isActive = true
        controller.view.rightAnchor.constraint(equalTo: view.rightAnchor).isActive = true
        controller.view.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
        controller.view.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        
        controller.didMove(toParentViewController: self)

    }
    
    private func instantiateCreateGameView() -> UIViewController? {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: CreateGameViewController.storyboardIdentifier) as? CreateGameViewController else { fatalError("Unable to instantiate an CreateGameViewController from the storyboard") }
        
        controller.delegate = self
        return controller

    }
    
    private func instantiateStartGameView() -> UIViewController? {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: StartGameViewController.storyboardIdentifier) as? StartGameViewController else { fatalError("Unable to instantiate an CreateGameViewController from the storyboard") }
        
        controller.delegate = self
        return controller
        
    }
    
    private func instantiateAnswerGameView(_ hangMessage: HangMessage) -> UIViewController? {
        guard let controller = storyboard?.instantiateViewController(withIdentifier: AnswerViewController.storyboardIdentifier) as? AnswerViewController else { fatalError("Unable to instantiate an CreateGameViewController from the storyboard") }
        controller.selectedHangMessage = hangMessage
        return controller
        
    }

    
    private func startConversation(_ messageLayout: MSMessageTemplateLayout, _ originalWord: String?,  _ hangWord: String?, _ hintText: String?,  _ removedCharacters: [String]?) {
        guard let conversation = activeConversation else { fatalError("Expected a conversation") }
        
        let components = HangMessage.constructComponents(originalWord, hangWord, hintText, removedCharacters)
        
        let message = MSMessage(session: conversation.selectedMessage?.session ?? MSSession())
        message.layout = messageLayout
        message.url = components.url!

        
        // Add the message to the conversation.
        conversation.insert(message) { error in
            if let error = error {
                print(error)
            }
        }
        
        dismiss()

    }
    
    // MARK: - StartGameViewController Delegate Methods

    func startGame(_ controller: StartGameViewController) {
        self.requestPresentationStyle(.expanded)
    }
    
    
    // MARK: - CreateGameViewController Delegate Methods
    
    func startConversation(_ controller: CreateGameViewController, _ messageLayout: MSMessageTemplateLayout, _ originalWord: String?, _ hangWord: String?,  _ hintText: String?, _ removedCharacters: [String]?) {
        startConversation(messageLayout, originalWord, hangWord, hintText, removedCharacters)

    }
    
}
